2025-06-07 03:57:17 - root - INFO - تم تهيئة نظام التسجيل بنجاح.
2025-06-07 03:57:17 - __main__ - INFO - ✅ البوت يعمل الآن...
2025-06-07 03:57:18 - apscheduler.scheduler - INFO - Scheduler started
2025-06-07 03:57:44 - utils.balance - INFO - تم تحديث رصيد المستخدم 780028688 بمقدار 100.0. الرصيد الجديد: 499.0.
2025-06-07 03:57:45 - utils.balance - INFO - المشرف 780028688 أضاف 100.0 إلى 780028688.
2025-06-07 03:58:24 - utils.balance - INFO - تم تحديث رصيد المستخدم 780028688 بمقدار -50.0. الرصيد الجديد: 449.0.
2025-06-07 03:58:24 - utils.balance - INFO - المشرف 780028688 خصم 50.0 من 780028688.
2025-06-07 04:00:38 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by setWebhook request
2025-06-07 04:00:42 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:00:44 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:00:49 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:00:53 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:00:59 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:01:07 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:01:19 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:01:37 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:02:03 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:02:34 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:03:04 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:03:35 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:04:05 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:04:36 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:05:07 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:05:37 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:06:08 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:06:38 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
2025-06-07 04:07:09 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 753, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 747, in do_action
    return action_cb_task.result()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 377, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 4366, in get_updates
    await self._post(
    ^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    ),
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 623, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\_bot.py", line 652, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 201, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Rmzi Al-shareef\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\request\_baserequest.py", line 384, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
